name: Build and Push Image
on: [ push,workflow_dispatch ]

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Shellcheck
      id: Shellcheck
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Run ShellCheck
          uses: ludeeus/action-shellcheck@master

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: vsftpd
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./Dockerfile

    # Podman Login action (https://github.com/redhat-actions/podman-login) also be used to log in,
    # in which case 'username' and 'password' can be omitted.
    - name: Push To docker.io
      id: push-to-docker
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: docker.io/osadal
        username: osadal
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-docker.outputs.registry-paths }}"
